/**
 * Assemble src/client.ts (namespaced SpotifyApiClient) and src/index.ts (barrel)
 * from codegen.json. Run after the resource modules exist.
 *
 * Run: npm run codegen:client
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import type { TagGroup } from './build-endpoints';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');

const { tags } = JSON.parse(readFileSync(resolve(pkgRoot, 'codegen.json'), 'utf8')) as { tags: TagGroup[] };

const clientTs = `// AUTO-GENERATED by scripts/gen-client.ts. Do not edit by hand.
import { SpotifyHttpClient } from './core';
import type { ClientConfig } from './types/common';
${tags.map((t) => `import { ${t.className} } from './resources/${t.filename}';`).join('\n')}

/**
 * The Spotify Data API client. Every endpoint is reachable through a typed
 * resource namespace, e.g. \`client.search.search({ q: 'daft punk' })\`.
 */
export class SpotifyApiClient extends SpotifyHttpClient {
${tags.map((t) => `  readonly ${t.namespace}: ${t.className};`).join('\n')}

  constructor(config: ClientConfig) {
    super(config);
${tags.map((t) => `    this.${t.namespace} = new ${t.className}(this);`).join('\n')}
  }
}

/** Convenience factory equivalent to \`new SpotifyApiClient(config)\`. */
export function createClient(config: ClientConfig): SpotifyApiClient {
  return new SpotifyApiClient(config);
}
`;

const indexTs = `// AUTO-GENERATED by scripts/gen-client.ts. Do not edit by hand.
export { SpotifyApiClient, createClient } from './client';
export { SpotifyHttpClient } from './core';
export { SpotifyApiError } from './errors';
export type { SpotifyApiErrorInit } from './errors';
export { PROVIDERS, resolveConfig, DEFAULT_USER_AGENT, DEFAULT_TIMEOUT_MS, DEFAULT_RETRIES, DEFAULT_RETRY_DELAY_MS } from './config';
export type { ResolvedConfig } from './config';
export { buildPath } from './resources/base';
export { normalizeId, normalizeIds } from './ids';
export { paginate, collect } from './pagination';
export type { PaginateOptions, PageFetcher } from './pagination';
// Explicit (not \`export *\`) so these SDK types always win over any identically
// named type quicktype may emit in ./generated/responses.
export type {
  Provider,
  FetchLike,
  SuccessEnvelope,
  ErrorEnvelope,
  QueryValue,
  QueryParams,
  IdList,
  RetryInfo,
  RequestOverrides,
  RequestOptions,
  ClientConfig,
} from './types/common';
export * from './generated/responses';
${tags.map((t) => `export * from './resources/${t.filename}';`).join('\n')}
`;

writeFileSync(resolve(pkgRoot, 'src/client.ts'), clientTs);
writeFileSync(resolve(pkgRoot, 'src/index.ts'), indexTs);
console.log(`Wrote src/client.ts and src/index.ts for ${tags.length} namespaces.`);
