/**
 * Turn the sampled fixtures into TypeScript response interfaces via quicktype.
 *
 * For each fixture <key>.json we extract the envelope `.data` payload, name it
 * <PascalKey>Data (matching codegen.json), and let quicktype infer one interface
 * per payload into src/generated/responses.ts. Also emits .codegen-typenames.json
 * (the set of generated type names) for the resource-module generator.
 *
 * Run: npm run codegen:types
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, basename } from 'node:path';
import type { TagGroup } from './build-endpoints';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const fixturesDir = resolve(pkgRoot, 'fixtures');
const payloadsDir = resolve(pkgRoot, 'payloads');
const outFile = resolve(pkgRoot, 'src/generated/responses.ts');
const typeNamesFile = resolve(pkgRoot, '.codegen-typenames.json');

const HEADER = `/* eslint-disable */
// AUTO-GENERATED by scripts/generate-types.ts (quicktype).
// Response payload types inferred from real sampled API responses.
// Do not edit by hand — re-run \`npm run codegen:types\`.
`;

/** True when a payload is just an upstream error envelope carrying no real data. */
function isErrorPayload(payload: unknown): boolean {
  if (typeof payload !== 'object' || payload === null || Array.isArray(payload)) return false;
  const rec = payload as Record<string, unknown>;
  const meaningful = Object.keys(rec).filter((k) => !['error', 'message', 'success', 'status'].includes(k));
  return Boolean(rec.error) && meaningful.length === 0;
}

const ROOT_TYPE = 'SpotifyResponsesRoot';

function main() {
  const { tags } = JSON.parse(readFileSync(resolve(pkgRoot, 'codegen.json'), 'utf8')) as { tags: TagGroup[] };
  const keyToType = new Map<string, string>();
  for (const t of tags) for (const op of t.ops) keyToType.set(op.key, op.typeName);

  mkdirSync(resolve(pkgRoot, 'src/generated'), { recursive: true });
  if (existsSync(payloadsDir)) rmSync(payloadsDir, { recursive: true, force: true });
  mkdirSync(payloadsDir, { recursive: true });

  const fixtureFiles = existsSync(fixturesDir) ? readdirSync(fixturesDir).filter((f) => f.endsWith('.json')) : [];

  // One synthetic root object keyed by intended type name. Feeding quicktype a
  // single document lets us read back exactly which type it assigned each op,
  // so merged/deduped shapes still get their name via an alias.
  const root: Record<string, unknown> = {};
  const opTypeNames: string[] = [];

  for (const file of fixtureFiles) {
    const key = basename(file, '.json');
    const typeName = keyToType.get(key);
    if (!typeName) continue;
    const raw = JSON.parse(readFileSync(resolve(fixturesDir, file), 'utf8')) as unknown;
    const payload = typeof raw === 'object' && raw !== null && 'data' in raw ? (raw as { data: unknown }).data : raw;
    if (payload === undefined || payload === null || isErrorPayload(payload)) {
      console.log(`  drop   ${key} (empty/error payload)`);
      continue;
    }
    root[typeName] = payload;
    opTypeNames.push(typeName);
  }

  if (opTypeNames.length === 0) {
    writeFileSync(outFile, `${HEADER}\nexport {};\n`);
    writeFileSync(typeNamesFile, JSON.stringify([]));
    console.log('No usable fixtures — wrote empty responses.ts');
    return;
  }

  const rootFile = resolve(payloadsDir, 'root.json');
  writeFileSync(rootFile, JSON.stringify(root));

  const cmd = `npx --yes quicktype "${rootFile}" -o "${outFile}" --lang typescript --just-types --top-level ${ROOT_TYPE} --acronym-style original`;
  execSync(cmd, { stdio: 'inherit', cwd: pkgRoot });

  let body = readFileSync(outFile, 'utf8');

  // Extract the root interface and map each op type name -> the concrete type quicktype assigned.
  const rootMatch = body.match(new RegExp(`export interface ${ROOT_TYPE} \\{([\\s\\S]*?)\\n\\}`));
  const assigned = new Map<string, string>();
  if (rootMatch) {
    for (const line of rootMatch[1].split('\n')) {
      const m = line.match(/^\s*"?([A-Za-z0-9_]+)"?\??:\s*(.+?);\s*$/);
      if (m) assigned.set(m[1], m[2]);
    }
    // Drop the synthetic root interface from the shipped output.
    body = body.replace(rootMatch[0], '').replace(/\n{3,}/g, '\n\n');
  }

  const declared = new Set([...body.matchAll(/export\s+(?:interface|type)\s+([A-Za-z0-9_]+)/g)].map((m) => m[1]));

  const aliases: string[] = [];
  const present = new Set<string>();
  const unresolved: string[] = [];
  for (const typeName of opTypeNames) {
    if (declared.has(typeName)) {
      present.add(typeName);
      continue;
    }
    const expr = assigned.get(typeName);
    if (expr && expr !== typeName) {
      aliases.push(`export type ${typeName} = ${expr};`);
      present.add(typeName);
    } else {
      unresolved.push(typeName);
    }
  }

  const aliasBlock = aliases.length
    ? `\n// Endpoints whose response shape is identical to another — aliased to the shared type.\n${aliases.join('\n')}\n`
    : '';
  writeFileSync(outFile, `${HEADER}${aliasBlock}\n${body.trimStart()}`);
  writeFileSync(typeNamesFile, JSON.stringify([...present].sort(), null, 2));

  console.log(
    `Types: ${opTypeNames.length} sampled, ${present.size} named (${aliases.length} aliased), ${unresolved.length} unresolved -> unknown.`,
  );
  if (unresolved.length) console.log('  unresolved:', unresolved.join(', '));
}

main();
