// AUTO-GENERATED by scripts/gen-client.ts. Do not edit by hand.
import { SpotifyHttpClient } from './core';
import type { ClientConfig } from './types/common';
import { AiResource } from './resources/ai';
import { AlbumsResource } from './resources/albums';
import { AnalysisResource } from './resources/analysis';
import { ArtistsResource } from './resources/artists';
import { AudiobooksResource } from './resources/audiobooks';
import { BatchResource } from './resources/batch';
import { BrowseResource } from './resources/browse';
import { CacheResource } from './resources/cache';
import { ChartsResource } from './resources/charts';
import { ConcertsResource } from './resources/concerts';
import { CredentialsResource } from './resources/credentials';
import { DownloadsResource } from './resources/downloads';
import { EpisodesResource } from './resources/episodes';
import { HealthResource } from './resources/health';
import { LookupsResource } from './resources/lookups';
import { MarketsResource } from './resources/markets';
import { PartnerResource } from './resources/partner';
import { PlaylistsResource } from './resources/playlists';
import { SearchResource } from './resources/search';
import { ShowsResource } from './resources/shows';
import { SnapshotsResource } from './resources/snapshots';
import { TrackingResource } from './resources/tracking';
import { TracksResource } from './resources/tracks';
import { UsersResource } from './resources/users';
import { WebhooksResource } from './resources/webhooks';

/**
 * The Spotify Data API client. Every endpoint is reachable through a typed
 * resource namespace, e.g. `client.search.search({ q: 'daft punk' })`.
 */
export class SpotifyApiClient extends SpotifyHttpClient {
  readonly ai: AiResource;
  readonly albums: AlbumsResource;
  readonly analysis: AnalysisResource;
  readonly artists: ArtistsResource;
  readonly audiobooks: AudiobooksResource;
  readonly batch: BatchResource;
  readonly browse: BrowseResource;
  readonly cache: CacheResource;
  readonly charts: ChartsResource;
  readonly concerts: ConcertsResource;
  readonly credentials: CredentialsResource;
  readonly downloads: DownloadsResource;
  readonly episodes: EpisodesResource;
  readonly health: HealthResource;
  readonly lookups: LookupsResource;
  readonly markets: MarketsResource;
  readonly partner: PartnerResource;
  readonly playlists: PlaylistsResource;
  readonly search: SearchResource;
  readonly shows: ShowsResource;
  readonly snapshots: SnapshotsResource;
  readonly tracking: TrackingResource;
  readonly tracks: TracksResource;
  readonly users: UsersResource;
  readonly webhooks: WebhooksResource;

  constructor(config: ClientConfig) {
    super(config);
    this.ai = new AiResource(this);
    this.albums = new AlbumsResource(this);
    this.analysis = new AnalysisResource(this);
    this.artists = new ArtistsResource(this);
    this.audiobooks = new AudiobooksResource(this);
    this.batch = new BatchResource(this);
    this.browse = new BrowseResource(this);
    this.cache = new CacheResource(this);
    this.charts = new ChartsResource(this);
    this.concerts = new ConcertsResource(this);
    this.credentials = new CredentialsResource(this);
    this.downloads = new DownloadsResource(this);
    this.episodes = new EpisodesResource(this);
    this.health = new HealthResource(this);
    this.lookups = new LookupsResource(this);
    this.markets = new MarketsResource(this);
    this.partner = new PartnerResource(this);
    this.playlists = new PlaylistsResource(this);
    this.search = new SearchResource(this);
    this.shows = new ShowsResource(this);
    this.snapshots = new SnapshotsResource(this);
    this.tracking = new TrackingResource(this);
    this.tracks = new TracksResource(this);
    this.users = new UsersResource(this);
    this.webhooks = new WebhooksResource(this);
  }
}

/** Convenience factory equivalent to `new SpotifyApiClient(config)`. */
export function createClient(config: ClientConfig): SpotifyApiClient {
  return new SpotifyApiClient(config);
}
