// AUTO-GENERATED by scripts/gen-client.ts. Do not edit by hand.
export { SpotifyApiClient, createClient } from './client';
export { SpotifyHttpClient } from './core';
export { SpotifyApiError } from './errors';
export type { SpotifyApiErrorInit } from './errors';
export {
  PROVIDERS,
  resolveConfig,
  DEFAULT_USER_AGENT,
  DEFAULT_TIMEOUT_MS,
  DEFAULT_RETRIES,
  DEFAULT_RETRY_DELAY_MS,
} from './config';
export type { ResolvedConfig } from './config';
export { buildPath } from './resources/base';
export { normalizeId, normalizeIds } from './ids';
export { paginate, collect } from './pagination';
export type { PaginateOptions, PageFetcher } from './pagination';
// Explicit (not `export *`) so these SDK types always win over any identically
// named type quicktype may emit in ./generated/responses.
export type {
  Provider,
  FetchLike,
  SuccessEnvelope,
  ErrorEnvelope,
  QueryValue,
  QueryParams,
  IdList,
  RetryInfo,
  RequestOverrides,
  RequestOptions,
  ClientConfig,
} from './types/common';
export * from './generated/responses';
export * from './resources/ai';
export * from './resources/albums';
export * from './resources/analysis';
export * from './resources/artists';
export * from './resources/audiobooks';
export * from './resources/batch';
export * from './resources/browse';
export * from './resources/cache';
export * from './resources/charts';
export * from './resources/concerts';
export * from './resources/credentials';
export * from './resources/downloads';
export * from './resources/episodes';
export * from './resources/health';
export * from './resources/lookups';
export * from './resources/markets';
export * from './resources/partner';
export * from './resources/playlists';
export * from './resources/search';
export * from './resources/shows';
export * from './resources/snapshots';
export * from './resources/tracking';
export * from './resources/tracks';
export * from './resources/users';
export * from './resources/webhooks';
